<?php

use App\Pet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class PetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data_check = Pet::all()->first();
        if ($data_check != null) {
            Schema::disableForeignKeyConstraints();
            Pet::query()->truncate();
            Schema::enableForeignKeyConstraints();
        }
        $pets = array(
            array(
                'Slug' => 'chó_corgi_99',
                'Name' => 'Ban',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Chú chó chân ngắn đáng yêu năng động giống corgi này rất phù hợp với một gia đình cần tìm thêm một người bạn làm cho gia đình thêm vui vẻ nhộn nhịp',
                'Species' => 'Chó',
                'Breed' => 'Chó Corgi',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/ban1_a79xln.png',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_charlie_02',
                'Name' => 'Charlie',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Đây là một chú chó vô cùng đáng thương ',
                'Species' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/20c9fd65-77f3-4cf9-95ee-a35f323a76f8_tefufj',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_shiro_39',
                'Name' => 'Shiro',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đi lang thang trong phố cổ. Vô cùng thân thiện và quấn người.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/218960a7-977a-4aa8-8c69-69b4f2c907f3_llruvm',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_zin_03',
                'Name' => 'Zin',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé bị viêm gan đục hết một mắt, gãy chân trước thành tật, đi vòng tròn',
                'Species' => 'Chó',
                'Breed' => 'Phốc',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/ec1d4044-3451-4360-846d-3a2a1c6e96a0_q1s3kd',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_boo_38',
                'Name' => 'Boo',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé là cái, hơi nhút nhát. Nghiện nhưng khá ngại nên cần thời gian làm quen với người. Ăn uống tốt và đáng yêu xinh đẹp.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/a9dca6fd-62a3-414f-8bbb-d628e137be61_tqvto6',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_hayley_04',
                'Name' => 'Hayley',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé đi lạc đến một gia đình vào một ngày mưa gió. Được chủ nhà tốt bụng nhận nuôi',
                'Species' => 'Chó',
                'Breed' => 'Poodle',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/9233ce1a-57ab-4f6e-b29f-76b1baac6cbf_bqmgcw',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_ngao_37',
                'Name' => 'Ngáo',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Con là Ngáo, con đã biết ăn cơm giò và ăn hạt cho mèo dưới 4 tháng. Con biết đi vệ sinh đúng chỗ rồi ạ bé ngoan luôn vâng lời ạ. Con thích chơi cục rubik mini, mấy cuộn chỉ màu và thích đu ruy băng ạ.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/130cf0ec-a11c-44a3-9d3c-7ee483788f7a_swlpf3,PetCasa/PetThumbnails/aa37f93e-6a43-47ff-9548-5ba3a91cc193_kxfqvh,PetCasa/PetThumbnails/ce441ec7-65a5-42d6-9104-d59b832ab247_fd6qyk,PetCasa/PetThumbnails/2bfb9cc1-5a67-422a-97bf-04ac41f2f888_gmps9j',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_baba_05',
                'Name' => 'Baba',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé bull được 3 tháng, không đi được, do nằm một tư thế trong thời gian
                dài nên cơ thể bé bị biến dạng giống baba, lồng ngực xẹp xuống, 4 chân duỗi 4 phía, bé không thể
                lật được người . Da bị nấm và viêm nặng.',
                'Species' => 'Chó',
                'Breed' => 'Bull',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/332ad92b-abb7-42c1-99af-8d0549682183_tz41it',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_sua_36',
                'Name' => 'Sứa',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Con là Sứa, về cơ bản con giống y anh Sữa nhưng con có một hai cọng lông vàng lơ thơ trên đầu phải chú ý lắm mới thấy được. Con cũng ăn khoẻ ngủ khoẻ ị ngoan. Trò ưa thích của con là nhảy vào khay uống nước, nếu khay gần hết thì con ngủ luôn trong đó.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/f65c2c4f-6ad1-4fc4-8893-23c8069174ed_wodhgg,PetCasa/PetThumbnails/e240ebf9-fe00-491a-bf64-b7b4482c8a47_ku5qdq,PetCasa/PetThumbnails/703145fa-7681-4beb-8f94-2ed35e3c0d74_gac7ym',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_min_06',
                'Name' => 'Min',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đi lang thang trong đêm mưa. Một chị thấy thương quá báo tin cho nhóm đến bắt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/ab60010d-708d-4c2e-b4c3-f180db5c106a_uqurx8',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_doi_35',
                'Name' => 'Dồi',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Con là Dồi, con mẹ Vàng ạ. Lúc mới sinh con còi nhất trong ba anh em. Được mẹ Vàng sữa tốt và đồ ăn nhà sen cũng vừa miệng nên giờ con phổng phao lớn ghê rồi ạ. Con thích nghịch giỏ cói, thích ngủ trong ổ êm ấm, thích ăn xúc xích và cũng thích đu ruy băng ạ. Con đã biết ăn cơm, pate, hạt cho mèo baby và đi vệ sinh đúng chỗ gọn gàng rồi ba mẹ đón con về đi ạ.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/1c299fc0-4399-405b-ba41-f15941843f83_ly9sip,PetCasa/PetThumbnails/5880a2b5-9675-4c2b-b319-50b14e4e17c7_l5bxbh,PetCasa/PetThumbnails/fc909d61-53b9-4e84-b663-60924bc5bc2e_qng7v9',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_mario_07',
                'Name' => 'Mario',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bị nấm nặng, chân thiếu canxi gầy. Đi lạc được người dân bắt về rồi mang đến cho nhóm.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Poodle',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/420e28b9-8e81-47ac-8ba5-72aef546db46_glfw0z',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_map_34',
                'Name' => 'Mập',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Con là Mập, mẹ mất từ lúc sinh con nên con và em Còi được ghép cho mẹ Vàng chăm. Con ăn ngủ ngoan, biết ăn hạt baby, cơm thịt rau chén tất, biết đi vệ sinh đúng chỗ rồi ạ. Trộm vía con được mẹ Vàng chăm bụng núng na núng nính rồi.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/51c83288-5609-42fe-a82a-64e277a7cca4_mgxzfl,PetCasa/PetThumbnails/ff010b10-d340-455a-9b59-77d2166cc08c_os4xd3',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_bavi_08',
                'Name' => 'Bavi',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé được tình nguyện viên cứu từ Ba Vì về Hà Nội',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/ca5fb6e2-2442-445a-b898-2f0610555918_ngslrq',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_shin_33',
                'Name' => 'Shin',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đi lang thang vào nhà một bạn. Được nhóm đón lên phòng khám. Bé đang mang thai.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/d2ddf50e-f31d-4ac3-9949-c106756f3ec2_nfzrfd,PetCasa/PetThumbnails/7de145e1-3b45-4a7f-b676-6dc839f5fc4c_rk0rhi,PetCasa/PetThumbnails/6edd9dce-685f-426d-8300-91ab2363938c_lbsmhg',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_pupu_09',
                'Name' => 'Pupu',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé bị chủ bỏ lại phòng khám vì parvo. Hiện tại bé đã khoẻ mạnh, nhút nhát hiền lành và đáng yêu.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/29899b4d-6c64-4834-af12-77a09967a590_jldwb9,PetCasa/PetThumbnails/577096ad-3926-40db-86d4-4d79de7e0b65_cimn1r,PetCasa/PetThumbnails/4d8a0b81-fcf5-4d88-af11-a6dc0b70b5c7_tx1uuz',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_bot_32',
                'Name' => 'Bột',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bác hàng nước đối diện nói sáng nay có 2 thanh niên đi xe đến bỏ bé lại lề đường.
                Bé rất gầy, da bọc xương. Hai mũi chảy nước nhiều, bé ho và viêm phổi nặng. Người nhiều vết nấm và bị rận tai.
                Có lẽ bé đã không được chăm sóc tốt một thời gian dài.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo tây',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/d3b4c7ea-c6b9-4f80-afc4-b8cee895d3fc_ujm8sd,PetCasa/PetThumbnails/4b3e0390-aa19-4f2a-9601-58b83a82f314_s0tab4,PetCasa/PetThumbnails/10cae569-4342-4b72-9a68-19dc140bbf8c_vqnrot',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_chip_10',
                'Name' => 'Chip',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Một bạn báo tin có bé cún bị bỏ trước cửa nhà. Bé bị ve và giun. Từ lúc bạn báo tin tìm thấy cho đến
                khi bé về phòng khám, Chip vẫn ngơ ngơ ngác ngác không hiểu vì sao bị bỏ. Tính cách ngoan hiền dễ gần.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/49f669dd-588d-444d-941d-4e94332c3416_k1twv1,PetCasa/PetThumbnails/a83d026c-53c3-4617-b6a6-46c671b1ead1_ykp8t2,PetCasa/PetThumbnails/8f07b82d-1901-4aa9-8b11-66cdbeb806ef_jvau6q,PetCasa/PetThumbnails/d00cb333-e33a-4e97-a9c0-567d430df405_niz7u3',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_xu_31',
                'Name' => 'Xù',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đi ngoài ra sán, khá gầy.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo tây',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/91ad1263-5486-4b6a-bb18-c3adf4bbe68f_p4kkxl',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_bo_11',
                'Name' => 'Bơ',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Chủ cũ không chăm sóc, chân bị tật, đi khập khiễng.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Golden lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/2e11043f-56d3-48aa-b458-22b37c59dc1e_qxcifo',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_mochi_30',
                'Name' => 'Mochi',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đang mang thai, đi lang thang, bị chó đuổi.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/806f69a1-d6ca-4ed4-bb66-5600df01eb83_jfk3ns,PetCasa/PetThumbnails/c4fc14ae-444b-4dac-91c1-e92551e545d1_qurlhx',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_chen_12',
                'Name' => 'Chen',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Các bé học sinh trên đường đi học thấy Chen chạy lang thang một mình, người nấm toàn thân.
                Các em hỏi xung quanh không ai biết về Chen hay gia đình cũ của bé, nên Chen về với nhóm để điều trị và chăm sóc.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Bắc Kinh',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/1669f26f-8679-4c25-a6ba-4f204204d4f7_l7fply',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_bi_29',
                'Name' => 'Bi',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé bị đau mắt, anh chị đã chữa sắp khỏi. Tính cách vui vẻ, hiếu động và vô cùng yêu đời.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/df0f700d-56f2-4569-a07e-d4e94b6c87a7_ejshbe,PetCasa/PetThumbnails/b4068142-fd8f-42d0-8bbd-3f7d69bbcd56_f1uwvb,PetCasa/PetThumbnails/0ba09741-cd4c-4dec-80f5-fad2a4df8137_kptwgf,PetCasa/PetThumbnails/9abe447a-99dd-44e3-a9c6-e18314195142_eeqrdw',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_vang_13',
                'Name' => 'Vàng',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bị chủ bỏ lại phòng khám vì bị bệnh Parvo. Hiện tại bé đã khoẻ mạnh, thân thiện quấn người, vui vẻ.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/cc54fbde-f5d3-47ea-b6ec-ac77f46f20b8_lazniy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_ki_28',
                'Name' => 'Ki',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Có một bạn nhặt được bé mang đến cho nhóm.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/26799827-cc50-4bee-827d-b927079b391a_fhjgct,PetCasa/PetThumbnails/ed3cf099-d7fe-4564-ae84-57b63f9a5956_g3opui,PetCasa/PetThumbnails/fe3f57c8-bea4-44a2-baa8-b0596c8799e5_jff0ua',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_ve_14',
                'Name' => 'Ve',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé bị nhiều ve trên người, chủ bỏ không muốn nuôi nữa. Vô cùng hiền lành, nhút nhát.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/31c63c6d-d8f6-4de3-9226-af29a0155999_x8dghb,PetCasa/PetThumbnails/2ae5acf8-26db-4c76-abda-cc3037c3fba0_exzrsd',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_piggy_27',
                'Name' => 'Piggy',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé đi lang thang lạc trong chung cư.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/48c145f2-3dac-498d-818a-79fa1cf502e6_dx7stz,PetCasa/PetThumbnails/c4db2978-c35a-4402-a8a1-fd46a2d170e4_znx1ts',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_kiu_15',
                'Name' => 'Kiu',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé là chó hoang đang mang bầu, lang thang rồi trú tạm ở bãi rác cạnh vườn nhà một người dân. Bé sinh ra 2 bé cún, cả 3 vẫn được bác chủ nhà cho ăn hàng ngày. Nhưng bé nhát, không cho lại gần hẳn, trong khi ghẻ nặng trụi hết lông, người hôi rình, một chân lại bị gãy, nên cần hỗ trợ thuốc tại nhà.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/919d2d5f-0f89-4de3-8b3d-1b9ded26182c_wrim9r',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_mon_26',
                'Name' => 'Mon',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé bị câu trộm móc họng chảy nhiều máu.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo tây',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/1ddd421f-7a54-41a7-aaf4-24c1cc1acf32_htvg2k',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_binh_16',
                'Name' => 'Binh',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Hai chân sau của bé bị tật do bẩm sinh, bé vẫn chạy hoặc đi được. Hiện bé đang ở shelter của Yêu Động Vật tại Quảng Bình.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Chó ta',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/0bf66396-769b-4a18-8788-4597b7e604fd_dz8lb2',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_tabi_25',
                'Name' => 'Tabi',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Tabi được tìm thấy lúc đêm hôm mưa gió, một chân thì gãy. Bác sĩ bảo chân con gãy lâu lắm rồi,
                không được chữa trị nên con đành phải sống với một chân bị tật thôi. Thế nhưng điều đấy chả ảnh hưởng gì đến con cả.
                Con vẫn hồn nhiên vui tươi, nghịch ngợm, còn rất yêu và quấn người nữa.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/2bf2dc9a-787b-43ff-ad45-d30d0e2ab16f_coaxta',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_biscuit_17',
                'Name' => 'Biscuit',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Chủ đi nước ngoài, không thể nuôi mang đến nhờ nhận nuôi.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Sóc',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/14e900fc-d70e-45a1-90d4-ace732fdccb5_o8bwwe,PetCasa/PetThumbnails/4c687328-3344-4e04-87d7-37e95f6e6873_amniyn,PetCasa/PetThumbnails/afb8fe8f-4bb0-474e-bd7f-cf9c77f6c797_x8xbgo',
                'Age' => \Carbon\Carbon::now()->addDays(-2000),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_yoda_24',
                'Name' => 'Yoda',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Yoda ham vui ham chơi, thích nô đùa và khám phá mọi ngóc ngách trong nhà. "Mẹ nuôi" cứ đi đâu là bé theo đấy,
                 và còn thích mèo méo meo nói chuyện nữa cơ, nên đảm bảo nuôi bé là không bao giờ thấy lonely cô đơn đâu.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/download_1_tgqlk6',
                'Age' => \Carbon\Carbon::now()->addDays(-2000),
                'Sex' => 'Đực',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_chaplin_18',
                'Name' => 'Chaplin',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé chạy lang thang một mình, bị lạc. Nhóm không tìm thấy chủ và đã nhận về chăm sóc',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/f25685dd-5891-4ef8-8e6b-d49499f5a112_fvriut',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_beagano_23',
                'Name' => 'Beagan',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Mẹ của Beagan là mèo hoang, được chúng mình cứu về khi đang bụng mang dạ chửa, lang thang xin ăn.
                Beagan trông thì nghịch nhưng thực ra bé có tâm hồn mong manh nhạy cảm. Lúc nào bé cũng rất nhẹ nhàng, tình cảm, và thích được ôm.
                Bé đang dần dạn dĩ tự tin hơn, và thích khám phá mọi chỗ trong nhà. Rất quấn người, còn thích leo vào trong lòng "mẹ nuôi" nằm để được ôm nựng nữa cơ.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo ba tư',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/download_hejcg3',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_cami_19',
                'Name' => 'Cami',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Bé cún Cami bị bỏ rơi khi mới 3 tháng tuổi vì bị Parvo. Bé từng bị thiếu hụt canxi nhưng đã hồi phục. Sau hai lần đổi foster, bé hiện đã được nhận nuôi.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/16a23c90-34ba-489e-bccd-2c49ec60877e_yhmt9j,PetCasa/PetThumbnails/35e4e0b3-bae0-46b0-8e9c-b713935f52e2_apg0db,PetCasa/PetThumbnails/a43e4039-7af4-419b-a53c-8ed7ec721269_yuc3es,PetCasa/PetThumbnails/c165bff6-7484-4677-8ab3-678aff16edaa_vqerza,PetCasa/PetThumbnails/c95f6801-977e-450e-9e80-4506c89d76c8_bkry6n',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_xuka_22',
                'Name' => 'Xuka',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé bị yếu chân',
                'Species' => 'Mèo',
                'Breed' => 'Mèo lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/a37980ee-66cb-493b-82db-b97b18c94bcd_fibzfz',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_max_20',
                'Name' => 'Max',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Đây là bé chó nhóm cứu từ đợt trước Tết. Khi được TNV tìm thấy trên đường, bé bị nhiều vết khâu trên cổ và tai trong tình trạng nhiễm trùng nặng. Rất may là sau thời gian chữa trị, hiện tại bé đã khỏe mạnh, chỉ còn vết khâu trên cổ sắp liền hẳn. Max rất ngoan, biết nghe lời và hết sức thân thiện với mọi người mặc dù bé từng bị đối xử không tốt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/dfac3121-761a-4c1a-a794-d24a817f53dc_lfy3yb,PetCasa/PetThumbnails/e3af6a15-d2cc-4979-8eb0-ee74c6f28465_rmjbql,PetCasa/PetThumbnails/a6129866-d9ec-493b-946a-5c2e8da71ef5_b2pwzz,PetCasa/PetThumbnails/30d2bd16-6d72-4220-9fc7-4f96ffe2c4c5_gkfahc,PetCasa/PetThumbnails/36f7f971-6932-4d0c-854a-133fe864957d_zkzezy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_darwin_40',
                'Name' => 'Darwin',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Một đôi bạn nước ngoài thấy bé mèo con bị bỏ rơi ngoài đường, bé tí ti lại gầy yếu, nên đem về chăm sóc và liên hệ nhóm nhờ hỗ trợ. Bé được đặt tên là Darwin.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/4da972a4-de8a-41d4-a431-50559110b4b0_ewzi9f',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 1,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_darwin_disable_40',
                'Name' => 'Darwin',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Một đôi bạn nước ngoài thấy bé mèo con bị bỏ rơi ngoài đường, bé tí ti lại gầy yếu, nên đem về chăm sóc và liên hệ nhóm nhờ hỗ trợ. Bé được đặt tên là Darwin.',
                'Species' => 'Mèo',
                'Breed' => 'Mèo mướp',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/4da972a4-de8a-41d4-a431-50559110b4b0_ewzi9f',
                'Age' => \Carbon\Carbon::now()->addDays(-150), // Duới 6 tháng
                'Sex' => 'Cái',
                'Neutered' => 'Có',
                'Status' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_max_disable_20',
                'Name' => 'Max',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Đây là bé chó nhóm cứu từ đợt trước Tết. Khi được TNV tìm thấy trên đường, bé bị nhiều vết khâu trên cổ và tai trong tình trạng nhiễm trùng nặng. Rất may là sau thời gian chữa trị, hiện tại bé đã khỏe mạnh, chỉ còn vết khâu trên cổ sắp liền hẳn. Max rất ngoan, biết nghe lời và hết sức thân thiện với mọi người mặc dù bé từng bị đối xử không tốt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/dfac3121-761a-4c1a-a794-d24a817f53dc_lfy3yb,PetCasa/PetThumbnails/e3af6a15-d2cc-4979-8eb0-ee74c6f28465_rmjbql,PetCasa/PetThumbnails/a6129866-d9ec-493b-946a-5c2e8da71ef5_b2pwzz,PetCasa/PetThumbnails/30d2bd16-6d72-4220-9fc7-4f96ffe2c4c5_gkfahc,PetCasa/PetThumbnails/36f7f971-6932-4d0c-854a-133fe864957d_zkzezy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_max_disable_23',
                'Name' => 'Max',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Đây là bé chó nhóm cứu từ đợt trước Tết. Khi được TNV tìm thấy trên đường, bé bị nhiều vết khâu trên cổ và tai trong tình trạng nhiễm trùng nặng. Rất may là sau thời gian chữa trị, hiện tại bé đã khỏe mạnh, chỉ còn vết khâu trên cổ sắp liền hẳn. Max rất ngoan, biết nghe lời và hết sức thân thiện với mọi người mặc dù bé từng bị đối xử không tốt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/dfac3121-761a-4c1a-a794-d24a817f53dc_lfy3yb,PetCasa/PetThumbnails/e3af6a15-d2cc-4979-8eb0-ee74c6f28465_rmjbql,PetCasa/PetThumbnails/a6129866-d9ec-493b-946a-5c2e8da71ef5_b2pwzz,PetCasa/PetThumbnails/30d2bd16-6d72-4220-9fc7-4f96ffe2c4c5_gkfahc,PetCasa/PetThumbnails/36f7f971-6932-4d0c-854a-133fe864957d_zkzezy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_max_disable_23',
                'Name' => 'Max',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Đây là bé chó nhóm cứu từ đợt trước Tết. Khi được TNV tìm thấy trên đường, bé bị nhiều vết khâu trên cổ và tai trong tình trạng nhiễm trùng nặng. Rất may là sau thời gian chữa trị, hiện tại bé đã khỏe mạnh, chỉ còn vết khâu trên cổ sắp liền hẳn. Max rất ngoan, biết nghe lời và hết sức thân thiện với mọi người mặc dù bé từng bị đối xử không tốt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/dfac3121-761a-4c1a-a794-d24a817f53dc_lfy3yb,PetCasa/PetThumbnails/e3af6a15-d2cc-4979-8eb0-ee74c6f28465_rmjbql,PetCasa/PetThumbnails/a6129866-d9ec-493b-946a-5c2e8da71ef5_b2pwzz,PetCasa/PetThumbnails/30d2bd16-6d72-4220-9fc7-4f96ffe2c4c5_gkfahc,PetCasa/PetThumbnails/36f7f971-6932-4d0c-854a-133fe864957d_zkzezy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 2,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'cho_max_disable_23',
                'Name' => 'Max',
                'CertifiedPedigree' => 'Có',
                'Description' => 'Đây là bé chó nhóm cứu từ đợt trước Tết. Khi được TNV tìm thấy trên đường, bé bị nhiều vết khâu trên cổ và tai trong tình trạng nhiễm trùng nặng. Rất may là sau thời gian chữa trị, hiện tại bé đã khỏe mạnh, chỉ còn vết khâu trên cổ sắp liền hẳn. Max rất ngoan, biết nghe lời và hết sức thân thiện với mọi người mặc dù bé từng bị đối xử không tốt.',
                'SpeciesSort' => 'Chó',
                'Breed' => 'Phú Quốc Lai',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/dfac3121-761a-4c1a-a794-d24a817f53dc_lfy3yb,PetCasa/PetThumbnails/e3af6a15-d2cc-4979-8eb0-ee74c6f28465_rmjbql,PetCasa/PetThumbnails/a6129866-d9ec-493b-946a-5c2e8da71ef5_b2pwzz,PetCasa/PetThumbnails/30d2bd16-6d72-4220-9fc7-4f96ffe2c4c5_gkfahc,PetCasa/PetThumbnails/36f7f971-6932-4d0c-854a-133fe864957d_zkzezy',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 2,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
        );
        $single_pet = array(
            array(
                'Slug' => 'cho_rosie_01',
                'Name' => 'Rosie',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé thuộc bầy 5 cún. Mẹ của mấy bé bị cẩu tặc bắt đi từ lúc con chưa cai sữa. 5 bé con nheo nhóc phải đi gửi bú nhờ và chăm bộ. Chúng con chỉ là chó ta thôi, không phải tây hay lai gì cả.',
                'Species' => 'Chó',
                'Breed' => 'Sóc',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/rosie_01_n9vflt,PetCasa/PetThumbnails/rosie_02_wy1fx9',
                'Age' => \Carbon\Carbon::now()->addDays(-150),
                'Sex' => 'Cái',
                'Neutered' => 'Không',
                'Status' => 2,
                'AccountID' => 2,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
            array(
                'Slug' => 'meo_do_21',
                'Name' => 'Đô',
                'CertifiedPedigree' => 'Không',
                'Description' => 'Bé được chuộc ở chợ Hà Đông, bị dính giảm bạch cầu',
                'Species' => 'Mèo',
                'Breed' => 'Mèo tây',
                'Vaccinated' => 'Có',
                'Thumbnails' => 'PetCasa/PetThumbnails/8d3abd3a-f21b-424e-bb92-dbbe7c7f4a9d_kavkcj',
                'Age' => \Carbon\Carbon::now()->addDays(-540),
                'Sex' => 'Đực',
                'Neutered' => 'Không',
                'Status' => 2,
                'AccountID' => 2,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ),
        );
        Pet::insert($single_pet);
        Pet::insert($pets);
    }
}
