<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ChangePasswordRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'oldPassword' => 'required',
            'newPassword' => 'required',
            'newPassword2' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'oldPassword.required' => 'Vui lòng nhập mật khẩu cũ',
            'newPassword.required' => 'Vui lòng nhập mật khẩu mới',
            'newPassword2.required' => 'Vui lòng nhập lại mật khẩu mới',
        ]; // TODO: Change the autogenerated stub
    }
}
