<?php

namespace App\Http\Requests;

use App\Account;
use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
//    protected $redirectRoute = "admin_404";
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
//        dd($this->request);
        return [
            'FullName'    => 'required',
            'Email'       => 'required|email',
            'Password'    => 'required|min:6',
            'Address'     => 'required|min:2',
            'DateOfBirth' => 'required',
            'PhoneNumber' => 'required|mobile_vn',
            'IDNo'        => 'required|id_vn',
        ];
    }

    public
    function messages()
    {
        return [
            'IDNo.required' => 'Identify Number field is required',
            'IDNo.id_vn'    => 'Identify Number must is ID VietNam'
        ]; // TODO: Change the autogenerated stub
    }

    public
    function withValidator($validator)
    {
        if ($validator->fails()) {
            return;
        } else {
            $validator->after(
                function ($validator) {
                    $find_account = Account::where('Email', $this->Email)->get()->first();
                    if ($find_account != null) {
                        if ($find_account->Email) {
                            return $validator->errors()->add('Email', 'Email này đã được sử dụng!');
                        }
                    }
                });
        }
    }
}
