<?php

namespace App\Http\Requests;

use App\Account;
use Illuminate\Foundation\Http\FormRequest;

class UpdateAccountRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'FullName' => 'required',
            'Email' => 'required|email',
            'avatar' => 'required',
            'Address' => 'required|min:2',
            'DateOfBirth' => 'required|min:6',
            'PhoneNumber' => 'required|mobile_vn',
            'IDNo' => 'required|id_vn',
        ];
    }
    public function messages()
    {
        return [
            'IDNo.required' => 'Identify Number field is required',
            'IDNo.id_vn' => 'Identify Number must is ID VietNam'
        ]; // TODO: Change the autogenerated stub
    }

    public function withValidator($validator)
    {
        if($validator->fails()){
            return ;
        }else{
            $validator->after(
                function ($validator) {
                $find_account = Account::where('Email',$this->Email)->where('Slug','!=',$this->Slug)->get()->first();
                    if ($find_account != null) {
                        if ($find_account->Email){
                        return $validator->errors()->add('Email', 'This email have been already used !');
                    }
                }
            });
        }
    }
}
